2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_setup.py:_flush():77] Current SDK version is 0.18.1
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_setup.py:_flush():77] Configure stats pid to 146448
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_setup.py:_flush():77] Loading settings from /home/parsa/.config/wandb/settings
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_setup.py:_flush():77] Loading settings from /home/parsa/projects/MLAcceleratedNumericalSim/SEA:StateExchangeAttention/SEA/wandb/settings
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_setup.py:_flush():77] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-09-18 23:57:57,940 WARNING MainThread:146448 [wandb_setup.py:_flush():77] Could not find program at -m main
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m main'}
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_init.py:_log_setup():532] Logging user logs to /home/parsa/projects/MLAcceleratedNumericalSim/SEA:StateExchangeAttention/SEA/wandb/run-20240918_235757-6vz1wd0m/logs/debug.log
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_init.py:_log_setup():533] Logging internal logs to /home/parsa/projects/MLAcceleratedNumericalSim/SEA:StateExchangeAttention/SEA/wandb/run-20240918_235757-6vz1wd0m/logs/debug-internal.log
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_init.py:init():616] calling init triggers
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_init.py:init():623] wandb.init called with sweep_config: {}
config: {'device': 'cpu', 'case_name': 'cylinder_flow', 'project_name': 'SEA_CylinderFlow', 'save_dir': './checkpoints', 'field_data_path': '/home/parsa/projects/MLAcceleratedNumericalSim/SEA:StateExchangeAttention/data/CF/field_data.npy', 'input_path': '/home/parsa/projects/MLAcceleratedNumericalSim/SEA:StateExchangeAttention/data/CF/input_data.npy', 'coordinates_path': '/home/parsa/projects/MLAcceleratedNumericalSim/SEA:StateExchangeAttention/data/CF/coordinates.npy', 'train_fraction': 0.6, 'val_fraction': 0.2, 'random_seed': 42, 'dimension': '2D', 'field_groups': [[0, 1], [2]], 'scale_feature_range': None, 'csv_scale_name': 'scaler', 'm': 5, 'n': 5, 'k': None, 'pad_id': -1, 'pad_field_value': 0, 'num_fields': 12, 'MLP_ratio': 4, 'num_layers': 12, 'embed_dim': 128, 'n_heads': 8, 'block_size': 10, 'test_mesh_structure': False, 'perform_initial_test': True, 'validation_interval': 1, 'final_save': False, 'batch_size': 128, 'learning_rate': 0.0001, 'KL_weight_min': 0, 'KL_weight_max': 0, 'epoch_num': 100, 'use_wandb': True, 'run_name': 'encoder_decoder'}
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_init.py:init():666] starting backend
2024-09-18 23:57:57,940 INFO    MainThread:146448 [wandb_init.py:init():670] setting up manager
2024-09-18 23:57:57,941 INFO    MainThread:146448 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-18 23:57:57,942 INFO    MainThread:146448 [wandb_init.py:init():678] backend started and connected
2024-09-18 23:57:57,943 INFO    MainThread:146448 [wandb_init.py:init():773] updated telemetry
2024-09-18 23:57:57,948 INFO    MainThread:146448 [wandb_init.py:init():806] communicating run to backend with 90.0 second timeout
2024-09-18 23:57:58,143 ERROR   MainThread:146448 [wandb_init.py:init():832] encountered error: failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-09-18 23:57:58,143 ERROR   MainThread:146448 [wandb_init.py:init():1251] error in wandb.init()
Traceback (most recent call last):
  File "/home/parsa/miniforge/envs/MLEnhancedCFD/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1241, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/parsa/miniforge/envs/MLEnhancedCFD/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 838, in init
    raise error
wandb.errors.CommError: failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-09-18 23:57:59,795 WARNING MsgRouterThr:146448 [router.py:message_loop():77] message_loop has been closed
